### ISSUE TITLE
missing header FrankaError.h

### ISSUE THREAD

**Issue by christian-rauch** [facontidavide/type_introspection_tests#3]
On `master` branch I get the compilation error:
```
[workspace]/src/type_introspection_tests/example/franka.cpp:1:10: fatal error: ros_introspection_test/FrankaError.h: No such file or directory
 #include <ros_introspection_test/FrankaError.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

This was introduced after 09bc3cd713e6fafc86c13adc94b5117a42d982e3.

**Comment by facontidavide** [comment]
fixed
